from deepClassifier.components.data_ingestion import DataIngestion 
from deepClassifier.components.prepare_base_model import PrepareBaseModel
from deepClassifier.components.prepare_callback import PrepareCallback
from deepClassifier.components.training import Training
from deepClassifier.components.evaluation import Evaluation